baseURL = "https://null-mind.com/"
languageCode = "en"
title = "0xMoonrise"

disableKinds = ["taxonomy", "term"]

[params]
  description = "Hi, feel free to read everything I wrote! :)"

[markup]
  [markup.highlight]
    noClasses = false
    tabWidth = 4
    guessSyntax = false
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block  = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
 