baseURL = "https://null-mind.com/"
languageCode = "en"
title = "0xMoonrise"
uglyURLs = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Hi"
  projects = [
  "gochive",
  "asql",
  "simple_rc4",
]

[markup]
  [markup.highlight]
    noClasses = false
    tabWidth = 4
    guessSyntax = false
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block  = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]
 